base:
  install_dir: /opt
  mode: dev
  is_demo: false
  is_offline: false

remote_url:
  app_repo: https://apps-assets.fit2cloud.com
  repo_url: https://resource.fit2cloud.com/1panel/package/v2
  resource_url: https://resource.fit2cloud.com/1panel/resource/v2

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
