services:
  tensorrt-llm:
    image: ${IMAGE}:${VERSION}
    container_name: ${CONTAINER_NAME}
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - 1panel-network
    volumes:
      - ${MODEL_PATH}:/models
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
      stack: 67108864
    command: ${COMMAND}
networks:
  1panel-network:
    external: true